// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyGSGcVzDqLYaiqKNYy82_yll0worWYhA',
    appId: '1:1114114343:web:0d2daa61eb6f8e9198c102',
    messagingSenderId: '1114114343',
    projectId: 'aamusted-connect',
    authDomain: 'aamusted-connect.firebaseapp.com',
    storageBucket: 'aamusted-connect.appspot.com',
    measurementId: 'G-FCQ85B6HLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWV8wZvM8TygXFyOqLOqDUdUOxCBXPWoM',
    appId: '1:1114114343:android:b36e5859603be8d698c102',
    messagingSenderId: '1114114343',
    projectId: 'aamusted-connect',
    storageBucket: 'aamusted-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeJrzpscp6WCUgXGeGqvGNjOeYfgTSpGw',
    appId: '1:1114114343:ios:662d465334f0831d98c102',
    messagingSenderId: '1114114343',
    projectId: 'aamusted-connect',
    storageBucket: 'aamusted-connect.appspot.com',
    iosBundleId: 'com.example.aamusterConnect',
  );
}
